name: React Build

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        run: actions/checkout@v2
        
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
